name: Build Android

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Add .npmrc file
        run: echo -e $NPMRC > ~/.npmrc
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm ci

      - name: Prepare app for build
        run: ionic capacitor sync android --prod

      - name: Make gradlew executable
        working-directory: ./android
        run: chmod +x ./gradlew

      - uses: sparkfabrik/android-build-action@v1.4.0
        if: inputs.PRODUCTION_RELEASE == false
        with:
          build-type: "assemble"
          gradle-task: "assembleDebug"
          increment-build-number: false
          # package-name: "com.example.app"
          # keystore-content: "keystore file content as base64 encoded string"
          # keystore-password: "keystore password"
          # key-alias: "keystore alias"
          # json-key-data: "JSON keystore file content"
          upload-to-play-store: false
          project-path: './android/'
          output-path: wfnews-dev-${{ github.sha }}.apk
          browserstack-upload: false
          # browserstack-username: ""
          # browserstack-access-key: ""
          fastlane-env: "debug"
          ruby-version: "head"
          bundler-version: "2.3"
          release-track: "internal"
          release-status: "draft"

      - uses: actions/upload-artifact@v3
        with:
          name: wfnews-dev-${{ github.sha }}.apk
          path: './android/wfnews-dev-${{ github.sha }}.apk'
  